epochs: 50
batch_size: 32
vocab_size: 25
task: sol  # hemo, sol, nf
debug: false

network:
  hidden_size: 480
  hidden_layers: 12
  attn_heads: 12
  dropout: 0.15

optim:
  lr: 1.0e-5

sch:
  name: lronplateau  # onecycle, lronplateau
  factor: 0.1
  patience: 4
